<div id="brands" class="grid_24 alpha omega">
    <div class="grid_3 alpha brand-title"><?=$this->__("Brand")?></div>
    <div class="grid_21 omega">
        <div class="horizontal carousel flexslider">
            <ul id="footer-brand" class="slides">
                <?php foreach($this->showAllBrands() as $brand):?>
                    <li class="itemslider"><a href="<?=$brand['url']?>"><img title="<?=$brand['name']?>" src="<?=$brand['img_src']?>" alt="<?=$brand['name']?>" height="58"/></a></li>
                <?php endforeach;?>
            </ul>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery(window).load(function(){
        if(jQuery('#footer-brand').children().length){
            jQuery('#footer-brand').parent().csslider();
        }
    });
</script>